"use client";
import { useState } from "react";
import type { SiteSettings } from "@/lib/cms/site-settings";
import { SaveStatusPill, type SaveState } from "@/components/admin/AdminUI";
import { updateSiteSettingsAction } from "@/app/admin/(dashboard)/content/site-settings/actions";

export function SiteSettingsForm({ initial }: { initial: SiteSettings }) {
  const [form,setForm]=useState(initial); const [state,setState]=useState<SaveState>("idle");
  const set=(path:string,value:string)=>setForm(f=>{const n=structuredClone(f) as SiteSettings; const [group,locale,key]=path.split("."); (n as any)[group][locale][key]=value; return n;});
  async function save(){setState("saving");try{await updateSiteSettingsAction(form);setState("saved")}catch{setState("error")}}
  return <div className="grid gap-5">
    <section className="rounded-lg border border-border bg-surface p-4 sm:p-5"><h2 className="font-display text-xl font-semibold text-ink">Navigation</h2><p className="mt-1 text-sm text-muted">Change the main menu wording in each language.</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{(["en","fr"] as const).map(l=><div key={l} className="grid gap-3"><p className="text-xs font-bold uppercase tracking-wider text-muted">{l==='en'?'English':'French'}</p>{(["products","about","contact","whatsapp","reviewOrder"] as const).map(k=><label key={k} className="grid gap-1 text-sm font-medium text-ink-soft"><span>{k}</span><input value={form.navigation[l][k]??""} onChange={e=>set(`navigation.${l}.${k}`,e.target.value)} className="rounded border border-border px-3 py-2.5 text-sm text-ink"/></label>)}</div>)}</div></section>
    <section className="rounded-lg border border-border bg-surface p-4 sm:p-5"><h2 className="font-display text-xl font-semibold text-ink">Footer</h2><p className="mt-1 text-sm text-muted">Control the main footer message and headings.</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{(["en","fr"] as const).map(l=><div key={l} className="grid gap-3"><p className="text-xs font-bold uppercase tracking-wider text-muted">{l==='en'?'English':'French'}</p>{Object.keys(form.footer[l]).map(k=><label key={k} className="grid gap-1 text-sm font-medium text-ink-soft"><span>{k}</span><input value={(form.footer[l] as any)[k]??""} onChange={e=>set(`footer.${l}.${k}`,e.target.value)} className="rounded border border-border px-3 py-2.5 text-sm text-ink"/></label>)}</div>)}</div></section>
    <section className="rounded-lg border border-border bg-surface p-4 sm:p-5"><h2 className="font-display text-xl font-semibold text-ink">Search engines</h2><p className="mt-1 text-sm text-muted">Set the title and description shown in Google and when pages are shared.</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{(["en","fr"] as const).map(l=><div key={l} className="grid gap-3"><p className="text-xs font-bold uppercase tracking-wider text-muted">{l==='en'?'English':'French'}</p>{(["title","description","ogTitle","ogDescription"] as const).map(k=><label key={k} className="grid gap-1 text-sm font-medium text-ink-soft"><span>{k==='ogTitle'?'Social share title':k==='ogDescription'?'Social share description':k==='title'?'Site title':'Meta description'}</span>{k.includes('description')?<textarea rows={3} value={form.seo[l][k]} onChange={e=>set(`seo.${l}.${k}`,e.target.value)} className="rounded border border-border px-3 py-2.5 text-sm text-ink"/>:<input value={form.seo[l][k]} onChange={e=>set(`seo.${l}.${k}`,e.target.value)} className="rounded border border-border px-3 py-2.5 text-sm text-ink"/>}</label>)}</div>)}</div></section>
    <div className="sticky bottom-3 flex items-center justify-between rounded-lg border border-border bg-surface p-3 shadow-card"><SaveStatusPill state={state}/><button type="button" onClick={save} disabled={state==='saving'} className="rounded bg-brand px-5 py-2.5 text-sm font-semibold text-white hover:bg-brand-dark disabled:opacity-60">Save website settings</button></div>
  </div>;
}
